### ISSUE TITLE
IndexError in `make_plots` worker

### ISSUE THREAD

**Issue by douglatornell** [SalishSeaCast/SalishSeaNowcast#138]
Appeared after `numpy` in `nowcast-env` environment was updated to v1.24.

Occurs in worker invocation `make_plots nemo nowcast research`.

```python-traceback
2022-12-23 07:57:15,275 ERROR [make_plots] unexpected IndexError in make_figure:
Traceback (most recent call last):
  File "/SalishSeaCast/SalishSeaNowcast/nowcast/workers/make_plots.py", line 1102, in _calc_figure
    fig = fig_func(*args, **kwargs)
  File "/SalishSeaCast/SalishSeaNowcast/nowcast/figures/research/velocity_section_and_surface.py", line 112, in make_figure
    cbar = _plot_vel_section(
  File "/SalishSeaCast/SalishSeaNowcast/nowcast/figures/research/velocity_section_and_surface.py", line 240, in _plot_vel_section
    ax.fill_between(
  File "/SalishSeaCast/nowcast-env/lib/python3.10/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/SalishSeaCast/nowcast-env/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 5252, in fill_between
    return self._fill_between_x_or_y(
  File "/SalishSeaCast/nowcast-env/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 5180, in _fill_between_x_or_y
    for idx0, idx1 in cbook.contiguous_regions(where):
  File "/SalishSeaCast/nowcast-env/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 1262, in contiguous_regions
    idx, = np.nonzero(mask[:-1] != mask[1:])
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
```

**Comment by douglatornell** [comment]
This issue was resolved on 16-Apr-23 when a new Python 3.11 `nowcast-env` was built on `skookum`.
