### ISSUE TITLE
make_turbidity_file raises pandas._config.config.OptionError

### ISSUE THREAD

**Issue by douglatornell** [SalishSeaCast/SalishSeaNowcast#94]
Appeared in new env created 2-Mar-2022 for emergency deployment after `/SalishSeaCast` SSD failure.
pandas version that shows issue is 1.4.1.
pandas version in previous working env was likely 1.2.2.

```pytb
  2022-03-02 15:32:01,643 CRITICAL [make_turbidity_file] unhandled exception:
  Traceback (most recent call last):
    File "/data/SalishSeaCast/NEMO_Nowcast/nemo_nowcast/worker.py", line 391, in _do_work
      checklist = self.worker_func(
    File "/data/SalishSeaCast/SalishSeaNowcast/nowcast/workers/make_turbidity_file.py", line 111, in make_turbidity_file
      itdf = _interpTurb(tdf, idateDD, mthresh)
    File "/data/SalishSeaCast/SalishSeaNowcast/nowcast/workers/make_turbidity_file.py", line 164, in _interpTurb
      pd.set_option("precision", 9)
    File "/data/SalishSeaCast/nowcast-env/lib/python3.10/site-packages/pandas/_config/config.py", line 256, in __call__
      return self.__func__(*args, **kwds)
    File "/data/SalishSeaCast/nowcast-env/lib/python3.10/site-packages/pandas/_config/config.py", line 149, in _set_option
      key = _get_single_key(k, silent)
    File "/data/SalishSeaCast/nowcast-env/lib/python3.10/site-packages/pandas/_config/config.py", line 116, in _get_single_key
      raise OptionError("Pattern matched multiple keys")
  pandas._config.config.OptionError: Pattern matched multiple keys
```

**Comment by douglatornell** [comment]
This looks likely it is a result of not paying attention to the docs warning about regex pattern matching for option names:

> Regexp which should match a single option. Note: partial matches are supported for convenience, but unless you use the full option name (e.g. x.y.z.option_name), your code may break in future versions if new options with similar names are introduced.

(https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.set_option.html)

Prior to 1.4.0, `precision` matched `display.precision`. The addition of `styler.format.precision` in 1.4.0 made `precision` have no unique match.

**Comment by douglatornell** [comment]
On reflection, the other question that arises is why setting the display precision is even being done in a worker module. I'm guessing that it is a leftover from development; perhaps copied in from notebook code.

It seems reasonable to resolve this issue by simply deleting line 164.
